# Generated by Django 5.2 on 2025-05-10 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('period', models.CharField(blank=True, choices=[('DAILY', 'Ежедневно'), ('WEEKLY', 'Еженедельно'), ('MONTHLY', 'Ежемесячно')], max_length=16, null=True, verbose_name='Период')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('penalty_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_task', to='tasks.task', verbose_name='Штрафная задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
                ('expired', models.BooleanField(verbose_name='Просрочено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completion', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Выполнение задачи',
                'verbose_name_plural': 'Выполнения задач',
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('period__isnull', False), ('date__isnull', False), _connector='OR'), models.Q(('date__isnull', False), ('period__isnull', False), _negated=True)), name='period_or_date_and_not_both'),
        ),
    ]
