# Generated by Django 5.2 on 2025-05-21 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletion',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 1), verbose_name='Когда'),
            preserve_default=False,
        ),
    ]
