# Generated by Django 5.2 on 2025-11-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'default_related_name': 'snippets', 'ordering': ('-created',), 'verbose_name': 'Сниппет', 'verbose_name_plural': 'Сниппеты'},
        ),
        migrations.AlterModelOptions(
            name='snippetscategory',
            options={'ordering': ('-created',), 'verbose_name': 'Категория сниппетов', 'verbose_name_plural': 'Категории сниппетов'},
        ),
    ]
